In [1]:
import numpy as np
import matplotlib.pyplot as plt
from math import *

In [35]:
## On redéfinit les ondelettes
import numpy as np
import pywt
class wavelet:

    # -----------------------------------
    # Class constructor	
    # -----------------------------------
    def __init__(self, wavename):

        self.wavename = wavename	
        self.set_filters()

    # -----------------------------------
    # Creates the filters associated to the wavelet	
    # -----------------------------------		
    def set_filters(self):

        w = pywt.Wavelet(self.wavename)
        self.dec_high = w.dec_hi
        self.dec_low = w.dec_lo
        self.rec_high = w.rec_hi
        self.rec_low = w.rec_lo	

**Question 1**\
Pour montrer que, pour tout $j \in \mathbb{Z}$, $(\phi_{j,k})_{k \in \mathbb{Z}}$ est une base orthonormée de $V_j$, il suffit de montrer que :
1) pour $j \in \mathbb{Z}$, $(\phi_{j,k})_{k \in \mathbb{Z}}$ est une famille orthonormée
2) $\forall (j,k) \in \mathbb{Z}^2, \phi_{j,k} \in V_j$
3) pour $j \in \mathbb{Z}$, $(\phi_{j,k})_{k \in \mathbb{Z}}$ engendre $V_j$\


Point **1** : Soient $(j,k,l) \in \mathbb{Z}^3$ :\
$$\langle \phi_{j,k},\phi_{j,l} \rangle = \frac{1}{2^j} \int_{\mathbb{R}} \phi(\frac{t-2^jk}{2^j}) \phi(\frac{t-2^jl}{2^j}) dt$$
On effectue le changement de variable $u = \frac{t}{2^j}$ de sorte que $dt = 2^j \cdot du$ et il vient :\
$$
\langle \phi_{j,k},\phi_{j,l} \rangle = \int_{\mathbb{R}} \phi(u_k) \phi(u-l) du
=\langle \phi_{0,k},\phi_{0,l} \rangle
$$
Comme, par hypothèse, $(\phi_{0,k})_{k \in \mathbb{Z}}$ est orthonormée, il vient : \
$$\langle \phi_{j,k},\phi_{j,l} \rangle = \delta_{k,l}$$
Ce qui montre que $(\phi_{j,k})_{k \in \mathbb{Z}}$ est une famille orthonormée.\
\
Pour les points **2** et **3**, on procède par deux récurrences : une ascendante pour traiter les cas $j \geq 0$, et une descendante pour les cas $j \leq 0$. Comme la propriété d'*invariance par dilatation* est définie par une équivalence, ces deux récurrences sont très semblables. On ne traite donc ici que les cas $j \geq 0$ : \
On va montrer par récurrence sur $j \in \mathbb{N}$ les propriétés $P(j) = "\forall k \in \mathbb{Z}, \phi_{j,k} \in V_j"$ et $Q(j) = "(\phi_{j,k})_{k \in \mathbb{Z}}$ engendre $V_j"$\
Par hypothèse, on a $P(0)$ et $Q(0)$.
Soit $j \in \mathbb{Z}$. On suppose $P(j)$ et $Q(j)$: \
 - Soit $k \in \mathbb{Z}$. Par hypothèse de récurrence, $\phi_{j,k} \in V_j$. Par *invariance par translation*, $$(t \mapsto \phi_{j,k}(t-2^jk))\in V_{j+1}$$
 Or, pour $t\in \mathbb{R}$, $$\phi_{j,k}(t-2^jk) = \phi(\frac{t-2^jk-2^jk}{2^j})=\phi(\frac{t-2^{j+1}k}{2^j}) = \phi(2\frac{t-2^{j+1}k}{2^{j+1}})$$
 Par *invariance par dilatation*, $$t \mapsto \phi(\frac{t-2^{j+1}k}{2^{j+1}}) \in V_{j+1}$$
 ie $\phi_{j+1,k}\in V_{j+1,k}$, ce qui montre $Q(j+1)$.
  - Soit maintenant $f \in V_{j+1}$. Par *invariance par dilatation*, l'application $g:t \mapsto f(2t)$ est dans $V_j$. Par hypotjhèse de récurrence, il existe $(\lambda_k)_{k\in \mathbb{Z}}$ presque nulle telle que $$ g = \sum_{k\in \mathbb{Z}} \lambda_k \phi_{j,k}$$
  On a alors, pour tout $t \in \mathbb{R}$,
  $$ f(t) = \sum_{k\in \mathbb{Z}} \lambda_k \phi_{j,k}(\frac{t}{2})
   = \sum_{k\in \mathbb{Z}} \lambda_k \phi(\frac{t}{2^{j+1}}-k) 
   =\sum_{k\in \mathbb{Z}}\lambda_k \phi_{j+1,k}(t) $$
   Ce qui montre que $(\phi_{j+1,k})_{k\in \mathbb{Z}}$ engendre $V_{j+1}$.\
   \
   Par principe de récurrence, avec le point **1**, on a montré que, pour tout $j \in \mathbb{Z}$, $(\phi_{j,k})_{k \in \mathbb{Z}}$ est une base orthonormée de $V_j$.\
   \
   Exprimons à présent $\phi_{j+1,0}$ en fonction des $\phi_{j,k}$ : \
    - Par décroissance de la suite $(V_j)_{j \in \mathbb{Z}}$, on a $V_{j+1}\subset V_j$, donc, comme $(\phi_{j,k})_{k \in \mathbb{Z}}$ est une base (algébrique) orthonormée de $V_j$, $\phi_{j+1,0} = \sum_{k\in \mathbb{Z}} \langle \phi_{j+1,0},\phi_{j,k}\rangle \phi_{j,k}$ et cette somme n'a qu'un nombre fini de termes non-nuls.\
     - On fixe à présent $j \in \mathbb{Z}$ et, pour $k\in \mathbb{Z}$, on pose $h[k] = \langle \phi_{j+1,0},\phi_{j,k}\rangle$, qui dépend *a priori* de $j$. Soit $k\in \mathbb{Z}$ :
     $$h[k] = \int_{\mathbb{R}}\frac{1}{\sqrt{2^{2j+1}}}\phi(\frac{t}{2^{j+1}})\phi(\frac{t-2^jk}{2^j})dt$$
     On effectue alors le changement de variable $u= \frac{t}{2^j}$ de sorte que $du = \frac{dt}{2^j}$, et il vient
     $$h[k] = \int_{\mathbb{R}}\phi(\frac{u}{2})\phi(u-k)du$$
     qui est bien **indépendant de j**.
    Pour vérifier que $h$ est bien la réponse impulsionnelle (discrète) d'un filtre passe-bas (discret), on calcule sa *trasformée de Fourier en temps discret* et on vérifie qu'elle atténue les hautes fréquences : 
    
  

**Question 2**\
Soit $(j,k)\in \mathbb{Z}^2$. Par définition,
$$a_{j+1}[k] = \langle f,\phi_{j+1,0}(\cdot-2^{j+1}k)\rangle = \int_{\mathbb{R}}f(t)\phi_{j+1,0}(t-2^{j+1}k)dt\qquad(1)$$
On introduit la *relation d'échelle* : pour $t\in \mathbb{R}$
$$\phi_{j+1,0}(t-2^{j+1}k) = \sum_{p\in \mathbb{Z}}h[p]\phi_{j,p}(t-2^{j+1}k)$$
On réexprime à présent tout en fonction de la fonction $\phi$ : pour $p\in\mathbb{Z}$,
$$\phi_{j,p}(t-2^jk) = \frac{1}{\sqrt{2^j}}\phi(\frac{t-2^{j+1}k-2^jp}{2^j})$$
$$=\frac{1}{\sqrt{2^j}}\phi(\frac{t-2^j(2k+p)}{2^j})$$
$$=\phi_{j,2k+p}(t)$$
On remplace dans $(1)$ : 
$$a_{j+1}[k] =  \int_{\mathbb{R}}f(t)\sum_{p\in \mathbb{Z}}h[p]\phi_{j,2k+p}(t)dt$$
On a vu que la somme dans l'expression ci-dessus n'a qu'un nombre fini de termes non-nuls. On peut donc sans scrupule interchanger somme et intégrale par linéarité de l'intégrale, et on obtient : 
$$a_{j+1}[k] =  \sum_{p\in \mathbb{Z}}h[p]\int_{\mathbb{R}}f(t)\phi_{j,2k+p}(t)dt $$
$$= \sum_{p\in \mathbb{Z}}h[p]a_j[2k+p]$$
Par le changement d'indice $n = p + 2k$, on réécrit ce résultat :
$$a_{j+1,k} = \sum_{n\in\mathbb{Z}}h[n-2k]a_j[n]$$

In [89]:
def convolution(x: np.ndarray, f: np.ndarray) -> np.ndarray:
    """
    Perform a 1D circular convolution between a signal and a filter.

    The signal is extended periodically in order to avoid boundary effects,
    and the result is cropped to preserve the original length of the signal.

    Parameters
    ----------
    x : np.ndarray
        One-dimensional input signal of length N.

    f : np.ndarray
        One-dimensional convolution filter of length L.

    Returns
    -------
    y : np.ndarray
        One-dimensional array of length N corresponding to the circular
        convolution of `x` with `f`.
    """
    N = x.size
    L = f.size
    x = np.pad(x,(0,2*L+N-1))
    f = np.pad(f,(0,2*N+L-1))
    return np.fft.ifft(np.fft.fft(x)*np.fft.fft(f))[:N]

In [81]:
## Test
h = np.array([1,2,3,4,5,6])
x = np.array([2,5,6,7,8])
xconc = np.array([2,5,6,7,8,2,5,6,7,8,2,5,6,7,8,2,5,6,7,8,2,5,6,7,8])
print(convolution(x,h))
print(np.convolve(xconc,h))

[ 2.00000000e+00-2.03012210e-15j  9.00000000e+00-3.91373276e-15j
  2.20000000e+01-6.91358512e-15j  4.20000000e+01-2.55718369e-15j
  7.00000000e+01-6.32217459e-15j  9.80000000e+01-4.31265320e-15j
  1.12000000e+02-2.63190988e-15j  1.03000000e+02-2.90238960e-15j
  8.20000000e+01+5.14327111e-15j  4.80000000e+01-3.11467357e-15j
  2.36847579e-15+4.06995783e-15j  2.87600631e-15+8.04308199e-15j
  2.70682947e-15+1.72815611e-15j  2.36847579e-15+7.66582196e-15j
  4.22942105e-15+5.69418340e-15j -1.08273179e-14+4.22683868e-15j
  0.00000000e+00+3.16594829e-15j  5.41365894e-15-1.34656096e-16j
 -1.08273179e-14+4.37889445e-15j  0.00000000e+00-7.37851025e-16j
  0.00000000e+00-8.54522219e-15j]
[  2   9  22  42  70 100 121 125 124 118 100 121 125 124 118 100 121 125
 124 118 100 121 125 124 118  98 112 103  82  48]


In [66]:
def conv(img: np.ndarray, wavename: str):
    """
    Apply a 1D wavelet analysis filter bank column-wise to a 2D image,
    followed by dyadic subsampling.

    This function performs the first step of a separable 2D wavelet transform.

    Parameters
    ----------
    img : np.ndarray
        2D input array of shape (NX, NY).

    wavename : str
        Name of the wavelet defining the analysis filters.

    Returns
    -------
    approx : np.ndarray
        Low-pass filtered and vertically subsampled image
        of shape (NX/2, NY).

    detail : np.ndarray
        High-pass filtered and vertically subsampled image
        of shape (NX/2, NY).
    """
    ondelette = wavelet(wavename)
    NX,NY = img.shape
    approx = np.empty((NX//2,NY),complex)
    detail = np.empty((NX//2,NY),complex)
    for j in range(NY):
        signal = img[:,j]
        approx_j = convolution(signal,np.array(ondelette.dec_low[::-1]))
        approx_j = [approx_j[i] for i in range(NX) if i%2 == 0]
        approx[:,j] = approx_j
        detail_j = convolution(signal,np.array(ondelette.dec_high[::-1]))
        detail_j = [detail_j[i] for i in range(NX)if i%2 == 0]
        detail[:,j]=detail_j
    return approx,detail


In [53]:
## Test de compatibilité
conv(np.array([[1,2,3,1],[4,5,6,1],[7,8,9,1],[1,1,1,1]]),'haar')

approx_j(4,)
approx_j2
approx_j(4,)
approx_j2
approx_j(4,)
approx_j2
approx_j(4,)
approx_j2


(array([[ 0.70710678+0.j,  1.41421356+0.j,  2.12132034+0.j,
          0.70710678+0.j],
        [ 7.77817459+0.j,  9.19238816+0.j, 10.60660172+0.j,
          1.41421356+0.j]]),
 array([[-0.70710678+0.j, -1.41421356+0.j, -2.12132034+0.j,
         -0.70710678+0.j],
        [-2.12132034+0.j, -2.12132034+0.j, -2.12132034+0.j,
          0.        +0.j]]))

In [67]:
def iconv_low(x: np.ndarray, wavename: str):
    """
    Low-pass synthesis filtering with upsampling.

    This function corresponds to the inverse operation of the low-pass
    analysis filter, used during wavelet reconstruction.

    Parameters
    ----------
    x : np.ndarray
        2D array of low-pass coefficients.

    wavename : str
        Name of the wavelet defining the synthesis filter.

    Returns
    -------
    y : np.ndarray
        Reconstructed signal after upsampling and low-pass filtering.
    """
    ondelette = wavelet(wavename)
    nx,NY = x.shape
    NX = 2*nx
    y = np.empty((NX,NY),complex)
    for j in range(NY):
        signal = x[:,j]
        approx_j = np.zeros(NX)
        for i in range(nx):
            approx_j[2*i] = signal[i] 
        y_j = convolution(approx_j,np.array(ondelette.rec_low[::-1]))
        y[:,j] = y_j
    return y
def iconv_high(x: np.ndarray, wavename: str):
    """
    High-pass synthesis filtering with upsampling.

    This function reconstructs high-frequency components during
    the inverse wavelet transform.

    Parameters
    ----------
    x : np.ndarray
        2D array of high-pass coefficients.

    wavename : str
        Name of the wavelet defining the synthesis filter.

    Returns
    -------
    y : np.ndarray
        Reconstructed signal after upsampling and high-pass filtering.
    """
    ondelette = wavelet(wavename)
    nx,NY = x.shape
    NX = 2*nx
    y = np.empty((NX,NY),complex)
    for j in range(NY):
        signal = x[:,j]
        approx_j = np.zeros(NX)
        for i in range(nx):
            approx_j[2*i] = signal[i] 
        y_j = convolution(approx_j,np.array(ondelette.rec_high[::-1]))
        y[:,j] = y_j
    return y
    

In [68]:
## Test
transfo = conv(np.array([[1,2,3,1],[4,5,6,1],[7,8,9,1],[1,1,1,1]]),'haar')
iconv_low(transfo[0],'haar') + iconv_high(transfo[1],'haar')
#on n'est vraiment pas loin : les lignes sont décalées vers le bas et la ligne extreme fait n'importe quoi ...

C:\Users\josep\AppData\Local\Temp\ipykernel_29928\1268483143.py:29: ComplexWarning: Casting complex values to real discards the imaginary part
  approx_j[2*i] = signal[i]
C:\Users\josep\AppData\Local\Temp\ipykernel_29928\1268483143.py:61: ComplexWarning: Casting complex values to real discards the imaginary part
  approx_j[2*i] = signal[i]


array([[-4.99600361e-16+0.j, -2.22044605e-16+0.j,  0.00000000e+00+0.j,
        -1.11022302e-16+0.j],
       [ 1.00000000e+00+0.j,  2.00000000e+00+0.j,  3.00000000e+00+0.j,
         1.00000000e+00+0.j],
       [ 4.00000000e+00+0.j,  5.00000000e+00+0.j,  6.00000000e+00+0.j,
         1.00000000e+00+0.j],
       [ 7.00000000e+00+0.j,  8.00000000e+00+0.j,  9.00000000e+00+0.j,
         1.00000000e+00+0.j]])

In [83]:
def dwt2D(x: np.ndarray, wavename: str, dec_level=3):
    """
    Compute the 2D Discrete Wavelet Transform (DWT) of an image.

    The transform is implemented using separable 1D wavelet filter banks
    applied successively along columns and rows.

    Parameters
    ----------
    x : np.ndarray
        2D input image of shape (NX, NY).

    wavename : str
        Name of the wavelet used for decomposition.

    dec_level : int or float, optional
        Maximum number of decomposition levels.
        Default is 3.

    Returns
    -------
    coeff : list
        Multiscale wavelet coefficient structure:
        - coeff[0] to coeff[L-1]: detail coefficients [cH, cV, cD]
          at each scale (from finest to coarsest),
        - coeff[-1]: list containing the final coarse approximation [cA].
    """
    L = dec_level
    if L == 0 :
        coeff = [[x]] # a priori, pas besoin de faire une copie car rien ne se fait en place
    else :
        coeff = dwt2D(x,wavename,L-1)
        cA_precedent = coeff.pop()[0]#attention le dernier élément est une liste
        passe_bas_lignes,passe_haut_lignes = conv(cA_precedent.T,wavename)
        LL,LH = conv(passe_bas_lignes.T,wavename)
        HL,HH = conv(passe_bas_lignes.T,wavename)
        coeff += [[LH,HL,HH],[LL]]
    return coeff


In [104]:
from collections import deque
def idwt2D(coeff: list, wavename: str):
    """
    Reconstruct a 2D image from its wavelet coefficients.

    This function performs the inverse 2D discrete wavelet transform
    using separable synthesis filter banks.

    Parameters
    ----------
    coeff : list
        Wavelet coefficient structure as returned by `dwt2D`.

    wavename : str
        Name of the wavelet used for reconstruction.

    Returns
    -------
    x : np.ndarray
        Reconstructed 2D image.
    """
    L = len(coeff)-1
    if L == 0 :
        x = coeff[0][0]
    else :
        coeff = deque(coeff)
        [LH,HL,HH] = coeff.popleft() # details d'ordre 1
        print(LH.shape,HL.shape,HH.shape)
        LL = idwt2D(coeff,wavename) # approximation à l'ordre 1
        print(LL.shape)
        passe_bas_lignes = iconv_low(LL,wavename) + iconv_high(LH,wavename)
        passe_haut_lignes = iconv_low(HL,wavename)+iconv_high(HH,wavename)
        x = (iconv_low(passe_bas_lignes.T,wavename) + iconv_high(passe_haut_lignes.T,wavename)).T
    return x

In [105]:
## Test
x = np.array([[1,2,3,1],[4,5,6,1],[7,8,9,1],[1,1,1,1]])
print([[coeff.shape for coeff in liste]for liste in dwt2D(x,'haar',dec_level = 2)])
idwt2D(dwt2D(x,'haar',dec_level = 2),'haar')

[[(2, 2), (2, 2), (2, 2)], [(1, 1), (1, 1), (1, 1)], [(1, 1)]]
(2, 2) (2, 2) (2, 2)
(1, 1) (1, 1) (1, 1)
(1, 1)
(2, 2)


C:\Users\josep\AppData\Local\Temp\ipykernel_29928\1268483143.py:29: ComplexWarning: Casting complex values to real discards the imaginary part
  approx_j[2*i] = signal[i]
C:\Users\josep\AppData\Local\Temp\ipykernel_29928\1268483143.py:61: ComplexWarning: Casting complex values to real discards the imaginary part
  approx_j[2*i] = signal[i]


array([[-0.25+0.j, -0.25+0.j, -1.25+0.j, -1.25+0.j],
       [-0.25+0.j,  0.75+0.j, -1.25+0.j,  3.75+0.j],
       [-2.75+0.j,  1.25+0.j, -6.75+0.j,  4.25+0.j],
       [-2.75+0.j,  4.25+0.j, -6.75+0.j, 10.25+0.j]])